<svg>
  <g>
    <image
      width={600}
      href="https://app.dalekaobala.ba/assets/img/stolovi.png"
    />
  </g>
  <g>
    <image
      width={30}
      x={150}
      y={50}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>
  <g>
    <image
      width={30}
      x={200}
      y={50}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>
  <g>
    <image
      width={30}
      x={250}
      y={50}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>
  <g>
    <image
      width={30}
      x={380}
      y={50}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>
  <g>
    <image
      width={30}
      x={430}
      y={50}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>
  <g>
    <image
      width={30}
      x={480}
      y={50}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>

  <g>
    <image
      width={30}
      x={150}
      y={110}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>
  <g>
    <image
      width={30}
      x={200}
      y={110}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>
  <g>
    <image
      width={30}
      x={250}
      y={110}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>
  <g>
    <image
      width={30}
      x={380}
      y={110}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>
  <g>
    <image
      width={30}
      x={430}
      y={110}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>
  <g>
    <image
      width={30}
      x={480}
      y={110}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>

  <g>
    <image
      width={30}
      x={150}
      y={170}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>
  <g>
    <image
      width={30}
      x={150}
      y={230}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>
  <g>
    <image
      width={30}
      x={150}
      y={290}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>
  <g>
    <image
      width={30}
      x={150}
      y={350}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>
  <g>
    <image
      width={30}
      x={200}
      y={350}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>
  <g>
    <image
      width={30}
      x={250}
      y={350}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>
  <g>
    <image
      width={30}
      x={300}
      y={350}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>
  <g>
    <image
      width={30}
      x={350}
      y={350}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>
  <g>
    <image
      width={30}
      x={400}
      y={350}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>
  <g>
    <image
      width={30}
      x={450}
      y={350}
      href="https://e7.pngegg.com/pngimages/572/684/png-clipart-square-border-illustration-square-black-and-white-fuchsia-frame-miscellaneous-angle-thumbnail.png"
    />
  </g>
</svg>;
